### ISSUE TITLE
`require_relative': cannot load such file

### ISSUE THREAD

**Issue by maasha** [opentox/openbabel-gem#4]
A fresh install of the openbabel gem is acting up. What gives?

```
admin@milhouse:/usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/test$ ruby test_openbabel.rb
Traceback (most recent call last):
	5: from test_openbabel.rb:3:in `<main>'
	4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/lib/openbabel.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/lib/openbabel.rb:1:in `require_relative': cannot load such file -- /usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/openbabel/lib/openbabel (LoadError)
admin@milhouse:/usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/test$ ll /usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/openbabel/lib/openbabel
total 0
drwxr-xr-x    3 root  admin    96 Oct 11 15:20 .
drwxr-xr-x   11 root  admin   352 Oct 11 15:20 ..
drwxr-xr-x  126 root  admin  4032 Oct 11 15:20 2.4.90
admin@milhouse:/usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/test$ ll /usr/local/lib/ruby/gems/2.5.0/gems/openbabel-2.3.2.2/openbabel/lib/openbabel/2.4.90/
total 17808
drwxr-xr-x  126 root  admin    4032 Oct 11 15:20 .
drwxr-xr-x    3 root  admin      96 Oct 11 15:20 ..
-rwxr-xr-x    1 root  admin   35008 Oct 11 15:20 APIInterface.so
-rwxr-xr-x    1 root  admin   29784 Oct 11 15:20 CSRformat.so
-rwxr-xr-x    1 root  admin  107604 Oct 11 15:20 MCDLformat.so
...
```

**Comment by helma** [comment]
The latest OpenBabel version requires JSON libraries that are not available on all systems. In this case OpenBabel compilation fails. I have disabled the WITH_JSON compilation option, this should fix this issue.
